targets:
  $default:
    builders:
      i18n_generator:
        enabled: true
        options:
          path: assets/langs
          output: lib/src
          class_name: Translations

builders:
  i18n_generator:
    import: "package:i18n_generator/builder.dart"
    builder_factories: ["i18nGenerator"]
    build_extensions: { ".json": [".dart"] }
    auto_apply: dependents
    build_to: source
