targets:
  $default:
    builders:
      translations_keychain:
        enabled: true
        options:
          path: assets/langs
          output: lib/i18n
          class_name: TranslationsKeychain

builders:
  translations_keychain:
    import: "package:translations_keychain/translations_keychain.dart"
    builder_factories: ["keychainGenerator"]
    build_extensions: { ".json": [".dart"] }
    auto_apply: dependents
    build_to: source
