name: translations_keychain
description: A Dart builder to convert the JSON translation files into an abstract class for label suggestions.
version: 0.0.3
homepage: https://github.com/lcaprini/translations_keychain
issue_tracker: https://github.com/lcaprini/translations_keychain/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.2.2
  path: ^1.7.0
  basic_utils: ^2.5.3
  glob: ^1.2.0

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.8.1
  pedantic: ^1.9.0
