name: i18n_generator
description: A Dart builder to convert the JSON translation files into an abstract class for label suggestions.
version: 0.0.1
author: Luca Caprini <luca.caprini@gmail.com>
homepage: https://github.com/lcaprini/i18n_generator
issue_tracker: https://github.com/lcaprini/i18n_generator/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.2.2
  path:
  basic_utils: ^2.5.3

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.8.1
  pedantic: ^1.9.0
